CREATE TABLE IDENTITIES
(
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DISPLAY_NAME VARCHAR(255),
	EMAIL_ADDRESS VARCHAR(255),
	BIRTHDATE DATE,
	UID VARCHAR(25)
)